---
- name: Testing andrewrothstein.dapr
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'dapr --version'
      ansible.builtin.command: dapr --version
      changed_when: false
      register: dapr_test_output
    - name: Output from 'dapr --version'
      ansible.builtin.debug:
        msg: '{{ dapr_test_output.stdout }}'
