---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/dapr --version
    register: dapr_test_output
  - name: dapr --version
    debug:
      msg: '{{ dapr_test_output.stdout }}'
