---
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Looking for install at {{ dapr_install_exe }}
  become: true
  ansible.builtin.stat:
    path: '{{ dapr_install_exe }}'
  changed_when: false
  register: dapr_binary
- name: Downloading and installing dapr
  when: not dapr_binary.stat.exists
  block:
    - name: Downloading {{ dapr_url }} to {{ dapr_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ dapr_url }}'
        dest: '{{ dapr_tmp_archive }}'
        checksum: '{{ dapr_checksum }}'
        mode: '644'
    - name: Mkdir {{ dapr_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ dapr_install_dir }}'
        state: directory
        mode: '755'
    - name: Installing andrewrothstein.unarchivedeps
      ansible.builtin.include_role:
        name: andrewrothstein.unarchivedeps
    - name: Unarchiving {{ dapr_tmp_archive }} to {{ dapr_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ dapr_tmp_archive }}'
        dest: '{{ dapr_install_dir }}'
        creates: '{{ dapr_install_exe }}'
  always:
    - name: Rm -f {{ dapr_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ dapr_tmp_archive }}'
        state: absent
- name: Linking {{ dapr_link }} to {{ dapr_install_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ dapr_install_exe }}'
    dest: '{{ dapr_link }}'
    state: link
